### ISSUE TITLE
Multiple TCP clients

### ISSUE THREAD

**Issue by the-moog** [ryancwicks/PortRedirectorTool#2]
I don't know if this is a missing feature, or bug, but when I try and connect a 2nd client with this invocation I get an error.

PS ...\PortRedirectorTool\port_redirector\target\release> .\port_redirector_tool.exe -t serial -e COM6 -b 115200 -o 8001
DTR Set
Opened Serial listener on port COM6 at 115200 baud.
Starting TCP retransmission server at 0.0.0.0:8001
Accepted client connection at 127.0.0.1:52186
**thread 'tokio-runtime-worker' panicked at 'Can't start reciever loop more than once.', ...\PortRedirectorTool\port_redirector\src\retransmit_server.rs:58:73**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

In looking at this it seems the RUST_BACKTRACE thing does not work.

PS ...\PortRedirectorTool\port_redirector\target\release> set -Name RUST_BACKTRACE -Value 1
PS ...\PortRedirectorTool\port_redirector\target\release> .\port_redirector_tool.exe -t serial -e COM6 -b 115200 -o 8001
DTR Set
Opened Serial listener on port COM6 at 115200 baud.
Starting TCP retransmission server at 0.0.0.0:8001
Accepted client connection at 127.0.0.1:52338
thread 'tokio-runtime-worker' panicked at 'Can't start reciever loop more than once.', ...\PortRedirectorTool\port_redirector\src\retransmit_server.rs:58:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ryancwicks** [comment]
Aplogies for the delay in fixing this. I haven't looked at this project in awhile. I've fixed this problem with the most recent merge.
